In [ ]:
# for j in [1, cols]
#   for i in 1:rows
#     visible[i,j] = true
#   end
# end
# for i in [1, rows]
#   for j in 1:cols
#     visible[i,j] = true
#   end
# end

# for j in 2:cols-1
#   downwardColMax = trees[1,j]
#   for i in 2:rows-1
#     (canSeeFromSide, downwardColMax) = checkAndUpdateMax(trees[i,j], downwardColMax)
#     visible[i,j] = visible[i,j] || canSeeFromSide
#   end
#   upwardColMax = trees[rows,j]
#   for i in rows-1:-1:2
#     (canSeeFromSide, upwardColMax) = checkAndUpdateMax(trees[i,j], upwardColMax)
#     visible[i,j] = visible[i,j] || canSeeFromSide
#   end
# end
# for i in 2:rows-1
#   rightwardColMax = trees[i,1]
#   for j in 2:cols-1
#     (canSeeFromSide, rightwardColMax) = checkAndUpdateMax(trees[i,j], rightwardColMax)
#     visible[i,j] = visible[i,j] || canSeeFromSide
#   end
#   leftwardColMax = trees[i,cols]
#   for j in cols-1:-1:2
#     (canSeeFromSide, leftwardColMax) = checkAndUpdateMax(trees[i,j], leftwardColMax)
#     visible[i,j] = visible[i,j] || canSeeFromSide
#   end
# end



In [5]:
checkAndUpdateMax(val, cMax) =
  begin
    if (val <= cMax)
      return (false, cMax)
    else
      return (true, val)
    end
  end

mySign(x) =
  begin
    if (x > 0)
      return 2
    else
      return 1
    end
  end

mySign (generic function with 1 method)

In [70]:
input = readlines("input.txt")
(rows, cols) = length(input), length(input[1]) 
trees = zeros(Int8, rows, cols)
for i in 1:rows
  for j in 1:cols
    trees[i,j] = parse(Int8, input[i][j])
  end
end

In [7]:
# task 1
visible = fill(false, (rows, cols))
for j in 1:cols
  downwardColMax = -1
  for i in 1:rows
    (canSeeFromSide, downwardColMax) = checkAndUpdateMax(trees[i,j], downwardColMax)
    visible[i,j] = visible[i,j] || canSeeFromSide
  end
  upwardColMax = -1
  for i in rows:-1:1
    (canSeeFromSide, upwardColMax) = checkAndUpdateMax(trees[i,j], upwardColMax)
    visible[i,j] = visible[i,j] || canSeeFromSide
  end
end
for i in 1:rows
  rightwardColMax = -1
  for j in 1:cols
    (canSeeFromSide, rightwardColMax) = checkAndUpdateMax(trees[i,j], rightwardColMax)
    visible[i,j] = visible[i,j] || canSeeFromSide
  end
  leftwardColMax = -1
  for j in cols:-1:1
    (canSeeFromSide, leftwardColMax) = checkAndUpdateMax(trees[i,j], leftwardColMax)
    visible[i,j] = visible[i,j] || canSeeFromSide
  end
end
count(visible)

21

In [71]:
# task 2
checked = fill(false, (rows, cols))
movement = [(0,-1),(-1,0),(0,1),(1,0)]
seenFromAngles = Vector{Matrix{Int64}}()
for i in 1:4
  push!(seenFromAngles, zeros(Int64, rows, cols))
end

In [72]:
for j in 1:cols
  numRepeated = 1
  for i in 2:rows
    if (trees[i,j] > trees[i-1,j])
      seenFromAngles[1][i,j] += numRepeated 
      if (trees[i,j] > trees[i-numRepeated,j])
        seenFromAngles[1][i,j] += seenFromAngles[1][i-numRepeated, j]
      end
      numRepeated = 1
    elseif (trees[i,j] == trees[i-1, j])
      seenFromAngles[1][i,j] = 1
      numRepeated += 1
    else
      seenFromAngles[1][i,j] = 1
      numRepeated += 1
    end
  end
end

for i in 1:rows
  numRepeated = 1
  for j in 2:cols
    if (trees[i,j] > trees[i,j-1])
      seenFromAngles[2][i,j] += numRepeated 
      if (trees[i,j] > trees[i,j-numRepeated]) 
        seenFromAngles[2][i,j] += seenFromAngles[2][i, j-numRepeated]
      end
      numRepeated = 1
    elseif (trees[i,j] == trees[i, j-1])
      seenFromAngles[2][i,j] = 1
      numRepeated += 1
    else
      seenFromAngles[2][i,j] = 1
      numRepeated += 1
    end
  end
end

for j in 1:cols
  numRepeated = 1
  for i in rows-1:-1:1
    if (trees[i,j] > trees[i+1,j])
      seenFromAngles[3][i,j] += numRepeated 
      if (trees[i,j] > trees[i+numRepeated,j]) 
        seenFromAngles[3][i,j] += seenFromAngles[3][i+numRepeated, j]
      end
      numRepeated = 1
    elseif (trees[i,j] == trees[i+1, j])
      seenFromAngles[3][i,j] = 1
      numRepeated += 1
    else
      seenFromAngles[3][i,j] = 1
      numRepeated += 1
    end
  end
end

for i in 1:rows
  numRepeated = 1
  for j in cols-1:-1:1
    if (trees[i,j] > trees[i,j+1])
      seenFromAngles[4][i,j] += numRepeated 
      if (trees[i,j] > trees[i,j+numRepeated]) 
        seenFromAngles[4][i,j] += seenFromAngles[4][i, j+numRepeated]
      end
      numRepeated = 1
    elseif (trees[i,j] == trees[i, j+1])
      seenFromAngles[4][i,j] = 1
      numRepeated += 1
    else
      seenFromAngles[4][i,j] = 1
      numRepeated += 1
    end
  end
end

# for k in 1:4
#   (dx, dy) = movement[k]
#   leftRows = [1, rows][mySign(dx)]
#   rightRows = [1, rows][3 - mySign(dx)]
#   leftCols = [1, cols][mySign(dy)]
#   rightCols = [1, cols][3 - mySign(dy)]
#   for j=leftCols:dy:rightCols, i=leftRows:dx:rightRows
#     if (trees[i,j] > trees[i-1,j])
#       seenFromAngles[i,j] = numRepeated + seenFromAngles[i-numRepeated, j]
#       numRepeated = 1
#     else if (trees[i,j] == trees[i-1, j])
#       numRepeated += 1
#     else
#       seenFromAngles[k][i,j] = 1
#       numRepeated = 1
#     end
#   end

In [62]:
fillSeens(i,j) =
  begin
    checked[i,j] = true
    for k in 1:4 
      (dx, dy) = movement[k]
      if (Base.between(i+dx, 1, rows) && Base.between(j+dy, 1, cols) && !checked[i+dx,j+dy])
        fillSeens(i+dx, j+dy)
        if (trees[i,j]>trees[i+dx,j+dy])
          seenFromAngles[k][i,j] = seenFromAngles[k][i+dx, j+dy] + 1
        # else
        #   seenFromAngles[k][i,j] = 1
        end  
      end
      seenFromAngles[k][i,j] = max(seenFromAngles[k][i,j], 1)
    end
  end

fillSeens(1,1)

In [73]:
numSeen = ones(Int64, rows, cols)
for j in 1:cols
  for i in 1: rows
    for k in 1:4
      # seenFromAngles[k][i,j] = max(seenFromAngles[k][i,j], 1)
      numSeen[i,j] *= seenFromAngles[k][i,j]
    end
  end
end
findmax(numSeen)
# findmax(numSeen)[1]

(6776, CartesianIndex(59, 9))

In [74]:
numSeen

99×99 Matrix{Int64}:
 0    0    0    0    0   0    0     0  …    0    0    0    0    0    0  0
 0    1    2   12    1  72    1     1       1   45    1   15    1    2  0
 0   60   20    1   24   1    1   224      32    1    6    1   48    1  0
 0    8    1  192    1   4    9     4       6    5    1    3    1   72  0
 0    1    4    3   32  15  320     2       2  100    4    3    2    1  0
 0   24    1    1    4  60    1    30  …   24    1    4    1   96    2  0
 0    1   48    3  288   5   16    27     360   24    1    6   12   15  0
 0   30    1   16   63   1   14     4       2    2  252    2    1   18  0
 0    1  240    2    1   6    1    35       8    1    1   48   30    1  0
 0   42    1   36    9   2    1  1440      96   18    2    2   60    3  0
 0    1    4    1  400   1   18     1  …   56    1  288    1    1    3  0
 0   24    1    1   72  21    7     6       1  100    3   42   12    2  0
 0    1    8   36    2   1  192     1      90    1    1    5    3    1  0
 ⋮               

In [63]:
for k in 1:4
  display(seenFromAngles[k])
end

5×5 Matrix{Int64}:
 0  0  0  0  0
 1  1  1  1  1
 2  1  1  2  1
 1  1  2  3  3
 1  3  1  4  1

5×5 Matrix{Int64}:
 0  1  2  3  1
 0  1  1  1  4
 0  1  1  1  1
 0  1  2  1  4
 0  1  1  3  1

5×5 Matrix{Int64}:
 4  1  1  4  4
 1  1  3  1  1
 2  2  1  1  1
 1  1  1  1  1
 0  0  0  0  0

5×5 Matrix{Int64}:
 4  1  1  1  0
 1  1  2  1  0
 4  3  1  1  0
 1  1  2  1  0
 1  3  1  1  0

-1